# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"

[plugins.dotfiles-sync]
local = "~/.config/zsh"
use = ["{alias,func,env,opt,style}.zsh"]
apply = ["source"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
use = ['{{ name }}.zsh']
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ['{{ name }}.zsh']
apply = ["defer"]

[plugins.ohmyzsh-lib-clipboard]
github = "ohmyzsh/ohmyzsh"
use = ['lib/clipboard.zsh']
apply = ["defer"]

[plugins.ohmyzsh-lib-functions]
github = "ohmyzsh/ohmyzsh"
use = ['lib/functions.zsh']
apply = ["defer"]

#[plugins.ohmyzsh-aws]
#github = "ohmyzsh/ohmyzsh"
#use = ['plugins/aws/aws.plugin.zsh']
#apply = ["defer"]

[plugins.ohmyzsh-web-search]
github = "ohmyzsh/ohmyzsh"
use = ['plugins/web-search/web-search.plugin.zsh']
apply = ["defer"]

[plugins.pwp]
github = "ttkalcevic/pwp"
apply = ["defer"]

[plugins.replace-multiple-dots]
github = "momo-lab/zsh-replace-multiple-dots"
apply = ["defer"]
