# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[plugins.dotfiles-sync]
local = "~/.config/zsh"
use = ["{alias,func,env,opt,style}.zsh"]
apply = ["source"]

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit -d ~/.zcompdump"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
use = ['{{ name }}.zsh']
apply = ["defer"]

# Amazon-Qを使用する場合は競合するため無効にする必要がある。
# https://docs.aws.amazon.com/ja_jp/amazonq/latest/qdeveloper-ug/command-line-inline.html#command-line-inline-limits
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ['{{ name }}.zsh']
apply = ["defer"]

# https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/clipboard.zsh
[plugins.ohmyzsh-lib-clipboard]
github = "ohmyzsh/ohmyzsh"
use = ['lib/clipboard.zsh']
apply = ["defer"]

# https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/functions.zsh
[plugins.ohmyzsh-lib-functions]
github = "ohmyzsh/ohmyzsh"
use = ['lib/functions.zsh']
apply = ["defer"]

# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/web-search
[plugins.ohmyzsh-web-search]
github = "ohmyzsh/ohmyzsh"
use = ['plugins/web-search/web-search.plugin.zsh']
apply = ["defer"]

# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/copypath
[plugins.ohmyzsh-copypath]
github = "ohmyzsh/ohmyzsh"
use = ['plugins/copypath/copypath.plugin.zsh']
apply = ["defer"]

# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/copyfile
[plugins.ohmyzsh-copyfile]
github = "ohmyzsh/ohmyzsh"
use = ['plugins/copyfile/copyfile.plugin.zsh']
apply = ["defer"]

# https://github.com/ttkalcevic/pwp
[plugins.pwp]
github = "ttkalcevic/pwp"
apply = ["defer"]

# https://github.com/momo-lab/zsh-replace-multiple-dots
[plugins.replace-multiple-dots]
github = "momo-lab/zsh-replace-multiple-dots"
apply = ["defer"]
